name: 'kamidana-action'
description: 'jinja2 cli wrapper kamidana action.'
author: 'srz_zumix'
inputs:
  template:
    description: 'Jinja2 template file'
    required: true
  output_file:
    description: 'Output file path'
    required: false
  variables:
    description: 'Input data'
    required: false
  input_format:
    description: 'To be used with the "variables" input, can be one of: yaml,json,toml,csv,tsv,raw,env,md,markdown,spreadsheet'
    default: yaml
    required: false
  data_file:
    description: 'Input data file, supported format: yaml,json,toml'
    required: false
  requirements:
    description: 'Additionals modules requirements.txt string'
    require: false
  extensions:
    description: 'extension list, i18n,do,loopcontrols,with_,autoescape,debug'
    required: false
  additonals:
    description: 'Additionals modules'
    required: false
  dump_context:
    description: 'dumping loading data'
    default: false
    required: false
  debug:
    description: 'enable kamidana debug'
    default: false
    required: false

outputs:
  text:
    description: "kamidana output text"
    value: ${{ steps.kamidana.outputs.result }}

runs:
  using: "composite"
  steps:
    - name: setup-python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION || '3.10' }}
        cache: 'pip'
    - name: pip install
      env:
        INPUTS_REQUIREMENTS: ${{ inputs.requirements }}
      shell: bash
      run: |
        pip install -r ${GITHUB_ACTION_PATH}/requirements.txt
        if [ -n "${INPUTS_REQUIREMENTS}" ]; then
          echo "${INPUTS_REQUIREMENTS}" > "${RUNNER_TEMP}/requirements.txt"
          pip install -r "${RUNNER_TEMP}/requirements.txt"
        fi
    - name: kamidana
      shell: bash
      id: kamidana
      env:
        INPUTS_TEMPLATE: ${{ inputs.template }}
        INPUTS_OUTPUT_FILE: ${{ inputs.output_file }}
        INPUTS_VARIABLES: ${{ inputs.variables }}
        INPUTS_INPUT_FORMAT: ${{ inputs.input_format }}
        INPUTS_DATA_FILE: ${{ inputs.data_file }}
        INPUTS_EXTENSIONS: ${{ inputs.extensions }}
        INPUTS_ADDITONALS: ${{ inputs.additonals }}
        INPUTS_DUMP_CONTEXT: ${{ inputs.dump_context }}
        INPUTS_DEBUG: ${{ inputs.debug }}
        GITHUB_CONTEXT: ${{ toJson(github) }}
        JOB_CONTEXT: ${{ toJson(job) }}
        RUNNER_CONTEXT: ${{ toJson(runner) }}
      run: "${GITHUB_ACTION_PATH}/entorypoint.sh"

branding:
  icon: 'sliders'
  color: 'yellow'
