name: 'kamidana-action'
description: 'jinja2 cli wrapper kamidana action.'
author: 'srz_zumix'
inputs:
  template:
    required: true
  output_file:
    required: false
  variables:
    required: false
  format:
    description: 'To be used with the "variables" input, can be one of: yaml,json,toml,csv,tsv,raw,env,md,markdown,spreadsheet'
    required: false
    default: env
  data_file:
    description: 'support yaml, json, toml'
    required: false

runs:
  using: "composite"
  steps:
    - name: setup-python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION || '3.10' }}
        cache: 'pip'
    - name: pip install
      shell: bash
      run: |
        pip install -r ${GITHUB_ACTION_PATH}/requirements.txt
    - name: kamidana
      shell: bash
      env:
        INPUTS_TEMPLATE: ${{ inputs.template }}
        INPUTS_OUTPUT_FILE: ${{ inputs.output_file }}
        INPUTS_VARIABLES: ${{ inputs.variables }}
        INPUTS_FORMAT: ${{ inputs.format }}
        INPUTS_DATA_FILE: ${{ inputs.data_file }}
      run: "${GITHUB_ACTION_PATH}/entorypoint.sh"

branding:
  icon: 'sliders'
  color: 'yellow'
