name: Test
on:
  pull_request:


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: dump github.event
        run: |
          cat "${GITHUB_EVENT_PATH}"
      - uses: actions/checkout@v3
      - name: kamidana
        uses: ./
        with:
          template: testdata/test.j2
          output_file: test.txt
          data_file: ${{ env.GITHUB_EVENT_PATH }}
          data_format: json
      - run: cat test.txt
