name: Additionals-Example
on:
  pull_request:
  workflow_dispatch:

env:
  SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}

permissions:
  contents: read

jobs:
  additionals-example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: kamidana
        id: kamidana
        uses: ./
        with:
          template: testdata/additionals-example.j2
          output_file: test.txt
          tee: true
          requirements: |
            yurumikuji
            amaterasu-j2
          additonals: |
            yurumikuji.yurumikuji
            amaterasu.amaterasu
            testdata/surprised.py
      - run: |
          cat << 'EOS' | tee output.txt
          ${{ steps.kamidana.outputs.text }}
          EOS
          diff output.txt test.txt
