name: Deump-Context
on:
  pull_request:

jobs:
  default-example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: kamidana
        id: kamidana
        uses: ./
        with:
          template: testdata/default-example.j2
          output_file: test.txt
          dump_context: true
