name: IO-Example
on:
  pull_request:

jobs:
  io-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create TestData
        run: |
          cat << 'EOS' > io-test.j2
          {% set dirs = "." | listdir_dirs | list %}
          {% set len = dirs | length %}
          {%- for f in range(len) %}
          ./{{ dirs[f] }}
          {%- endfor %}
          EOS
      - name: kamidana
        id: kamidana
        uses: ./
        with:
          template: io-test.j2
          output_file: test.txt
          tee: true
      - run: |
          find . -type d -mindepth 1 -maxdepth 1 | tee output.txt
          diff output.txt test.txt

  io-example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: kamidana
        id: kamidana
        uses: ./
        with:
          template: testdata/io-example.j2
          output_file: test.txt
          tee: true
      - run: |
          cat << 'EOS' | tee output.txt
          ${{ steps.kamidana.outputs.text }}
          EOS
          diff output.txt test.txt

  io-example-wd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: kamidana
        id: kamidana
        uses: ./
        with:
          template: io-example.j2
          output_file: test.txt
          tee: true
          working-directory: testdata
      - run: |
          cat << 'EOS' | tee output.txt
          ${{ steps.kamidana.outputs.text }}
          EOS
          diff output.txt testdata/test.txt
