name: Release drafter
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  # write permission is required to create a github release
  contents: write
  # write permission is required for autolabeler
  # otherwise, read permission is required at least
  pull-requests: write
        
jobs:
  draft_release:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: release-drafter/release-drafter@v5
        id: release-drafter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish_release:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - uses: release-drafter/release-drafter@v5
        id: release-drafter
        with:
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
