name: Self Test
on:
  pull_request:

jobs:
  os-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: kamidana
        id: kamidana
        uses: ./
        with:
          template: testdata/default-example.j2
          output_file: test.txt
          tee: true
      - name: Test
        shell: bash
        run: |
          cat << 'EOS' | tee output.txt
          ${{ steps.kamidana.outputs.text }}
          EOS
          diff -w output.txt test.txt
          od -c output.txt | grep '\\r' || :
          echo "====="
          od -c test.txt   | grep '\\r' || :

  dump-context:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: kamidana
        id: kamidana
        uses: ./
        with:
          template: testdata/default-example.j2
          output_file: test.txt
          dump_context: true

  no-output-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: kamidana
        id: kamidana
        uses: ./
        with:
          template: testdata/default-example.j2
      - name: Test
        run: |
          git diff --exit-code
