name: Self Test
on:
  pull_request:

jobs:
  dump-context:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: kamidana
        id: kamidana
        uses: ./
        with:
          template: testdata/default-example.j2
          output_file: test.txt
          dump_context: true

  no-output-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: kamidana
        id: kamidana
        uses: ./
        with:
          template: testdata/default-example.j2
      - name:
