name: Test
on:
  pull_request:

env:
  SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: dump github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "${GITHUB_CONTEXT}" | tee github_context.json
      - name: kamidana
        id: kamidana
        uses: ./
        with:
          template: testdata/test.j2
          output_file: test.txt
          data_file: github_context.json
          requirements: |
            yurumikuji
            amaterasu-j2
          additonals: |
            yurumikuji.yurumikuji
            amaterasu.amaterasu
      - run: |
          echo "${{ steps.kamidana.outputs.text }}" | tee output.txt
          diff output.txt test.txt

