name: Variables-And-Multi-Data-File-Example
on:
  pull_request:

jobs:
  variables-and-multi-data-file-example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: kamidana
        id: kamidana
        uses: ./
        with:
          template: testdata/variables-and-data-file-example.j2
          output_file: test.txt
          tee: true
          data_files: |
            readme/replace-uses.json
            readme/links.json
          variables: |
            sample: test
            name: srz-zumix
      - run: |
          cat << 'EOS' | tee output.txt
          ${{ steps.kamidana.outputs.text }}
          EOS
          diff output.txt test.txt
